export const LANDING = "/";
export const SIGN_UP = "/signup";
export const SIGN_IN = "/signin";
export const HOME = "/home";
export const ACCOUNT = "/account";
export const ADMIN = "/admin";
export const PASSWORD_FORGET = "/pw-forget";
export const DEVICES = "/devices";
// Added by Rejohn
export const USERSLIST = "/users_list";
export const USERHOME = "/dashboard";
export const USERDEVICES = "/user_vehicle";
export const USERPROFILE = "/profile";
export const TEMPLATE = "/template";
export const APPSCREENSHOOT = "/screenshoot";
export const QUESTION = "/question";
export const TEAM = "/team";
export const TESTIMONIAL = "/testimonial";
// export const USERVEHICLEDETAIL = '/vehicle_details/';
